### PR TITLE
CWL update

### PR DESCRIPTION
**Pull request by MrGweep**
Updated the CWL workflow. Changes:
- CWL tracks the downloading of dataset during Preprocessing
- CWL tracks the checkpoints, ML Flow logging during Training

The CWL workflow gets trigger by adding the `--cwl` flag like that;
`micromamba run -p ./.venv python run-workflow.py -f use-cases/mnist/training-workflow.yml --cwl`

### CODE REVIEW

**Comment by matbun** [comment]
There is a conflict to resolve and I am afraid of doing it wrongly, so I'll leave it to you.

To include CWL into the automatic testing tool, could you please uncomment lines 28, 29, 43, 44 in this file? https://github.com/interTwin-eu/T6.5-AI-and-ML/blob/cwl-update/tests/use-cases/test_mnist.py

**Review by r-sarma — COMMENTED** [review]
The CWL integration is working properly.

**Review by matbun — APPROVED** [review]
CWL allows to add documentation by means of the `doc` field, whcih is a bit more "elegant" than YAML comments. However, this is a minor detail

**Comment by matbun** [comment]
Oh, I just forgot that the docs need to be updated as well before merging!

**Pull request merged**
